mcp:
  servers:
    my-local-tools:
      command: /opt/anaconda3/bin/python3
      args:
        - /Users/kentchiu/Documents/Github/new-openc/mcp-server/my_custom_tools.py
    mcp-fs:
      command: /opt/anaconda3/bin/python3
      args:
        - /Users/kentchiu/Documents/Github/new-openc/mcp_fs/server.py

openai:
  api_key: ollama
  base_url: http://localhost:11434/v1
  default_model: Nemotron-3-nano