services:
  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    restart: always

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      - "8085:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    depends_on:
      - redis
    restart: always

networks:
  searxng:
