workspace:
  # Root directory for all agent operations. All paths must be within this.
  root: /Users/kentchiu/Documents/Github/open_memo
  # Whether to restrict operations to workspace_root (safety feature)
  restrict_to_workspace: true

mcp:
  servers:

    file-tools:
      command: /opt/anaconda3/bin/python3
      args:
        - /Users/kentchiu/Documents/Github/open_memo/mcp_skill_agent/file_server.py
openai:
  api_key: ollama
  base_url: http://localhost:11434/v1
  default_model: qwen3-coder-next
  # qwen3-coder-next
  #GLM-4.7-Flash
  #gemma3:27b - not support tools
  #Nemotron-3-nano # not good enough for coding